---
name: CI

on:
  workflow_call:
    inputs:
      release_version:
        description: "Set version string for release"
        type: string
        default: ""
  workflow_dispatch:
    inputs:
      release_version:
        description: "Set version string for release"
        type: string
        default: ""
  push:
    branches: ["main"]
    paths:
      - "go.mod"
      - "go.sum"
      - "*.go"
      - "**/*.go"
  pull_request:
    branches: ["main"]
  merge_group:
    branches: ["main"]

jobs:
  lint:
    uses: heathcliff26/ci/.github/workflows/golang-lint.yaml@main
    with:
      os: windows-latest

  unit-tests:
    uses: heathcliff26/ci/.github/workflows/golang-unit-tests.yaml@main
    with:
      os: windows-latest

  build:
    uses: heathcliff26/ci/.github/workflows/golang-build.yaml@main
    needs:
      - lint
      - unit-tests
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
          - arch: arm64
    with:
      release: "${{ github.event_name == 'pull_request' && 'devel' || inputs.release_version == '' && 'rolling' || inputs.release_version }}"
      goos: "windows"
      goarch: "${{ matrix.arch }}"
      artifact: "bin/wsl2-ssh-pageant-${{ matrix.arch }}.exe"
      artifact-name: "wsl2-ssh-pageant-${{ matrix.arch }}"
      cmd: "hack/build.sh wsl2-ssh-pageant-${{ matrix.arch }}"
    secrets: inherit
