---
name: CI

on:
  workflow_call:
    inputs:
      release_version:
        description: "Set version string for release"
        type: string
        default: ""
  workflow_dispatch:
    inputs:
      release_version:
        description: "Set version string for release"
        type: string
        default: ""
  push:
    branches: ["main"]
    paths:
      - "go.mod"
      - "go.sum"
      - "*.go"
      - "**/*.go"
  pull_request:
    branches: ["main"]
  merge_group:
    branches: ["main"]

jobs:
  lint:
    uses: heathcliff26/ci/.github/workflows/golang-lint.yaml@main
    with:
      os: windows-latest

  unit-tests:
    uses: heathcliff26/ci/.github/workflows/golang-unit-tests.yaml@main
    with:
      os: windows-latest

  build:
    runs-on: ubuntu-latest
    needs:
      - lint
      - unit-tests
    steps:
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Setup golang
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version: 'stable'
          cache-dependency-path: go.sum

      - name: Build Artifact
        env:
          RELEASE_VERSION: "${{ inputs.release_version }}"
        run: hack/build.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: "wsl2-ssh-pageant.exe"
          path: "bin/wsl2-ssh-pageant.exe"
          retention-days: 1
          if-no-files-found: error
