---
name: CI

on:
  workflow_call:
    inputs:
      release_version:
        description: "Set version string for release"
        type: string
        default: ""
  workflow_dispatch:
    inputs:
      release_version:
        description: "Set version string for release"
        type: string
        default: ""
  push:
    branches: ["main"]
    paths:
      - "go.mod"
      - "go.sum"
      - "*.go"
      - "**/*.go"
  pull_request:
    branches: ["main"]
  merge_group:
    branches: ["main"]

jobs:
  lint:
    uses: heathcliff26/ci/.github/workflows/golang-lint.yaml@main
    with:
      os: windows-latest

  unit-tests:
    uses: heathcliff26/ci/.github/workflows/golang-unit-tests.yaml@main
    with:
      os: windows-latest

  build:
    runs-on: ubuntu-latest
    needs:
      - lint
      - unit-tests
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Setup golang
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: 'stable'
          cache-dependency-path: go.sum

      - name: Build Artifact
        env:
          RELEASE_VERSION: "${{ inputs.release_version }}"
        run: hack/build.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: "wsl2-ssh-pageant.exe"
          path: "bin/wsl2-ssh-pageant.exe"
          retention-days: 1
          if-no-files-found: error
