---
name: CI

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "go.mod"
      - "go.sum"
      - "*.go"
      - "**/*.go"
  pull_request:
    branches: ["main"]
  merge_group:
    branches: ["main"]

jobs:
  lint:
    uses: heathcliff26/ci/.github/workflows/golang-lint.yaml@main
    with:
      os: windows-latest

  build:
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup golang
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: 'stable'
          cache-dependency-path: go.sum

      - name: Build Artifact
        run: hack/build.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: "wsl2-ssh-pageant.exe"
          path: "bin/wsl2-ssh-pageant.exe"
          retention-days: 1
          if-no-files-found: error
