---
name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number for release"
        type: string
        required: true
      draft:
        description: "Create draft release"
        type: boolean
        default: true
      update:
        description: "Update existing release"
        type: boolean
        default: false

jobs:
  build:
    uses: ./.github/workflows/ci.yaml
    with:
      release_version: "${{ inputs.version }}"

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Download artifacts
        uses: actions/download-artifact@8caf195ad4b1dee92908e23f56eeb0696f1dd42d # v4.1.5
        with:
          path: bin
          merge-multiple: true

      - uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5 # v1.14.0
        with:
          allowUpdates: ${{ inputs.update }}
          artifacts: "bin/wsl2-ssh-pageant.exe"
          artifactErrorsFailBuild: true
          draft: ${{ inputs.draft }}
          generateReleaseNotes: true
          tag: "${{ inputs.version }}"
